@startuml
class InitProgram{
    + void start();
}

class Client
class Server

enum TypeConnection{
    SERVER
    CLIENT
}
abstract class Connection{
	{abstract} + string  receiveMessage();
	{abstract} + void sendMessage(string message);
}

class ConnectionServer{
}
class ConnectionClient{
}


class Message
class InformationMessage


class Game
class Player
class Cards
class MatrixMemory

class GUIServer
class GUIGame

InitProgram -- Client : > create
InitProgram -- Server : > create

Connection <-- ConnectionServer
Connection <-- ConnectionClient

@enduml
